#!/bin/sh
amixer -c 0 sset 'Left Mixer Left DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Right Mixer Left DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Right Mixer Right DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier Mixer' mute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier DAC' unmute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier Mute' unmute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier' 60% > /dev/null 2>&1;
amixer sset 'Master' 50%

#Check if fat32 is flagged as "dirty", and if so unmount, repair, remount
if dmesg | grep "mmcblk0p2" > /dev/null;  then
echo -e "\e[31mUnclean shutdown detected.\e[0m"
echo -e "\e[32mChecking NTFS partition...\e[0m"
umount /dev/mmcblk0p2
ntfsfix -b -d /dev/mmcblk0p2 > /dev/null; 
echo -e "\e[32mCheck complete.\e[0m"
fi

# Mount our partition
/bin/mount -t ntfs3 /dev/mmcblk0p2 /home/retrostone -o noatime,nodiratime,suid,dev,exec,async,uid=1000,gid=100,umask=022,fmask=022,dmask=022,discard,nls=utf8,prealloc,force

/usr/bin/key_driver &

cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "performance" > $file; done
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
