#!/bin/sh
amixer -c 0 sset 'Left Mixer Left DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Right Mixer Left DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Right Mixer Right DAC' mute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier Mixer' mute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier DAC' unmute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier Mute' unmute > /dev/null 2>&1;
amixer -c 0 sset 'Power Amplifier' 60% > /dev/null 2>&1;

#Check if fat32 is flagged as "dirty", and if so unmount, repair, remount
#if dmesg | grep "mmcblk0p2" > /dev/null;  then
#echo -e "\e[31mUnclean shutdown detected.\e[0m"
#echo -e "\e[32mChecking FAT32 partition...\e[0m"
#umount /dev/mmcblk0p2
#fsck.vfat -y /dev/mmcblk0p2 > /dev/null; 
#mount /dev/mmcblk0p2 /mnt -t vfat -o rw,sync,utf8
#echo -e "\e[32mCheck complete.\e[0m"
#fi

cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
for file in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo "performance" > $file; done
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
