#!/bin/sh

# Set CPU governor  to ondemand
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 1008000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 408000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 25 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy

/usr/bin/brightness_daemon &
#udevadm control --reload-rules
#udevadm trigger

/usr/sbin/parted -s "/dev/mmcblk0" "resizepart 2 -1"
/usr/bin/ntfsfix -d "/dev/mmcblk0p2"
/usr/bin/ntfsresize -i -f "/dev/mmcblk0p2"
/usr/bin/ntfsresize --force --force "/dev/mmcblk0p2"
/usr/bin/ntfsfix -d "/dev/mmcblk0p2"

# Mount our partition
/bin/mount -t ntfs3 /dev/mmcblk0p2 /home/retrostone -o noatime,nodiratime,suid,dev,exec,async,uid=1000,gid=100,umask=022,fmask=022,dmask=022,discard,nls=utf8,prealloc,force
