#!/bin/sh
export HOME=/home/retrostone
export SDL_NOMOUSE=1
START=/home/retrostone/autoexec.sh
#Check if fat32 is flagged as "dirty", and if so unmount, repair, remount
if dmesg | grep "mmcblk0p3" > /dev/null;  then
echo -e "\e[31mUnclean shutdown detected.\e[0m"
echo -e "\e[32mChecking FAT32 partition...\e[0m"
umount /dev/mmcblk0p3
fsck.vfat -y /dev/mmcblk0p3 > /dev/null; 
mount /dev/mmcblk0p3 /mnt -t vfat -o rw,sync,utf8
echo -e "\e[32mCheck complete.\e[0m"
fi

while [ 1 ]
do
	if test -f "$START"; then
		source $START
    	else
		cd $HOME/gmenu2x;
		./gmenu2x > /dev/null 2>&1;
	fi
        clear
done
