#!/bin/sh
export HOME=/mnt
export SDL_NOMOUSE=1
START=/mnt/autoexec.sh
#Check if fat32 is flagged as "dirty", and if so unmount, repair, remount
if dmesg | grep "mmcblk0p3" > /dev/null;  then
echo -e "\e[31mUnclean shutdown detected.\e[0m"
echo -e "\e[32mChecking FAT32 partition...\e[0m"
umount /dev/mmcblk0p3
fsck.vfat -y /dev/mmcblk0p3 > /dev/null; 
mount /dev/mmcblk0p3 /mnt -t vfat -o rw,sync,utf8
echo -e "\e[32mCheck complete.\e[0m"
fi
while [ 1 ]
do
	cd $HOME
	exec $START
    clear
done
